name: infof308-chrono
channels:
  - https://conda.anaconda.org/intel
  - https://conda.anaconda.org/projectchrono
  - https://conda.anaconda.org/conda-forge
dependencies:
  - python=3.9
  - numpy=1.23
  - irrlicht=1.8
  - pychrono=7.0
  - networkx=2.8
  - loguru=0.6
  - pip
  - pip:
    - pygad==2.19.1
    - black~=22.12
    - isort~=5.11
